name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create folder
        run: |
          mkdir -p ${{ github.workspace }}/output
          chmod 777 ${{ github.workspace }}/output
      - uses: docker/build-push-action@v2
        with:
          context: docker
          tags: jellyfin-tizen-build:latest
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: jellyfin-tizen-build:latest
          options: -v ${{ github.workspace }}/output:/output
          run: /tizen/package.sh
      - uses: actions/upload-artifact@v3
        with:
          name: Jellyfin-Tizen-Build
          path: ${{ github.workspace }}/output/Jellyfin.wgt
      - name: Show files in directories
        run: |
          find ${{ github.workspace }}

